services:
  caddy:
    image: caddy:2.10.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - frontend
      - backend

  backend:
    build: ./backend
    volumes:
      - /home/ubuntu/pokemon-card-bot/data:/app/data
      - ./backend/app:/code/app
    environment:
      - DATABASE_URL=/app/data/pokemon_cards.db
      - CARD_DATA_PATH=/app/data/pokemon_tcg_pocket_cards.csv
      - ACCESS_PASSWORD=pokemon123!!

  frontend:
    build: ./frontend
    user: "root"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - /home/ubuntu/pokemon-card-bot/data/card_images:/usr/share/nginx/html/card-images:ro
      - /home/ubuntu/webui-pokemon-card-bot/data/icons:/usr/share/nginx/html/icons:ro
    depends_on:
      - backend

volumes:
  caddy_data:

networks:
  default:
    name: pokemon-card-network