services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - frontend
      - backend

  backend:
    build: ./backend
    volumes:
      - /home/ubuntu/pokemon-card-bot/data:/app/data
    environment:
      - DATABASE_URL=/app/data/pokemon_cards.db
      - CARD_DATA_PATH=/app/data/pokemon_tcg_pocket_cards.csv

  frontend:
    build: ./frontend
    user: "root"
    volumes:
      - /home/ubuntu/pokemon-card-bot/data/card_images:/usr/share/nginx/html/card-images:ro
    depends_on:
      - backend

volumes:
  caddy_data:

networks:
  default:
    name: pokemon-card-network